# Define memory addresses to load from here

new_liscensee_codes = {
    '00': 'None',
    '1': 'Nintendo Research & Development 1',
    '8': 'Capcom',
    '13': 'EA (Electronic Arts)',
    '18': 'Hudson Soft',
    '19': 'B-AI',
    '20': 'KSS',
    '22': 'Planning Office WADA',
    '24': 'PCM Complete',
    '25': 'San-X',
    '28': 'Kemco',
    '29': 'SETA Corporation',
    '30': 'Viacom',
    '31': 'Nintendo',
    '32': 'Bandai',
    '33': 'Ocean Software/Acclaim Entertainment',
    '34': 'Konami',
    '35': 'HectorSoft',
    '37': 'Taito',
    '38': 'Hudson Soft',
    '39': 'Banpresto',
    '41': 'Ubi Soft1',
    '42': 'Atlus',
    '44': 'Malibu Interactive',
    '46': 'Angel',
    '47': 'Bullet-Proof Software2',
    '49': 'Irem',
    '50': 'Absolute',
    '51': 'Acclaim Entertainment',
    '52': 'Activision',
    '53': 'Sammy USA Corporation',
    '54': 'Konami',
    '55': 'Hi Tech Expressions',
    '56': 'LJN',
    '57': 'Matchbox',
    '58': 'Mattel',
    '59': 'Milton Bradley Company',
    '60': 'Titus Interactive',
    '61': 'Virgin Games Ltd.3',
    '64': 'Lucasfilm Games4',
    '67': 'Ocean Software',
    '69': 'EA (Electronic Arts)',
    '70': 'Infogrames5',
    '71': 'Interplay Entertainment',
    '72': 'Broderbund',
    '73': 'Sculptured Software6',
    '75': 'The Sales Curve Limited7',
    '78': 'THQ',
    '79': 'Accolade8',
    '80': 'Misawa Entertainment',
    '83': 'LOZC G.',
    '86': 'Tokuma Shoten',
    '87': 'Tsukuda Original',
    '91': 'Chunsoft Co.9',
    '92': 'Video System',
    '93': 'Ocean Software/Acclaim Entertainment',
    '95': 'Varie',
    '96': 'Yonezawa10/S’Pal',
    '97': 'Kaneko',
    '99': 'Pack-In-Video',
    '9H': 'Bottom Up',
    'A4': 'Konami (Yu-Gi-Oh!)',
    'BL': 'MTO',
    'DK': 'Kodansha'
}

cartridge_types = {
    '$00': 'ROM ONLY',
    '$01': 'MBC1',
    '$02': 'MBC1+RAM',
    '$03': 'MBC1+RAM+BATTERY',
    '$05': 'MBC2',
    '$06': 'MBC2+BATTERY',
    '$08': 'ROM+RAM',
    '$09': 'ROM+RAM+BATTERY',
    '$0B': 'MMM01',
    '$0C': 'MMM01+RAM',
    '$0D': 'MMM01+RAM+BATTERY',
    '$0F': 'MBC3+TIMER+BATTERY',
    '$10': 'MBC3+TIMER+RAM+BATTERY',
    '$11': 'MBC3',
    '$12': 'MBC3+RAM',
    '$13': 'MBC3+RAM+BATTERY',
    '$19': 'MBC5',
    '$1A': 'MBC5+RAM',
    '$1B': 'MBC5+RAM+BATTERY',
    '$1C': 'MBC5+RUMBLE',
    '$1D': 'MBC5+RUMBLE+RAM',
    '$1E': 'MBC5+RUMBLE+RAM+BATTERY',
    '$20': 'MBC6',
    '$22': 'MBC7+SENSOR+RUMBLE+RAM+BATTERY',
    '$FC': 'POCKET CAMERA',
    '$FD': 'BANDAI TAMA5',
    '$FE': 'HuC3',
    '$FF': 'HuC1+RAM+BATTERY'
}

ram_sizes = {
    '$00': '0',
    '$02': '8 KiB',
    '$03': '32 KiB',
    '$04': '128 KiB',
    '$05': '64 KiB'
}

destination = {
    '$00': 'Japan',
    '$01': 'Overseas',
}

old_liscensee_codes = {
    '00': 'None',
'01': 'Nintendo',
'08': 'Capcom',
'09': 'HOT-B',
'0A': 'Jaleco',
'0B': 'Coconuts Japan',
'0C': 'Elite Systems',
'13': 'EA (Electronic Arts)',
'18': 'Hudson Soft',
'19': 'ITC Entertainment',
'1A': 'Yanoman',
'1D': 'Japan Clary',
'1F': 'Virgin Games Ltd.',
'24': 'PCM Complete',
'25': 'San-X',
'28': 'Kemco',
'29': 'SETA Corporation',
'30': 'Infogrames',
'31': 'Nintendo',
'32': 'Bandai',
'33': 'Refer to new liscensee code',
'34': 'Konami',
'35': 'HectorSoft',
'38': 'Capcom',
'39': 'Banpresto',
'3C': 'Entertainment Interactive (stub)',
'3E': 'Gremlin',
'41': 'Ubi Soft',
'42': 'Atlus',
'44': 'Malibu Interactive',
'46': 'Angel',
'47': 'Spectrum HoloByte',
'49': 'Irem',
'4A': 'Virgin Games Ltd.',
'4D': 'Malibu Interactive',
'4F': 'U.S. Gold',
'50': 'Absolute',
'51': 'Acclaim Entertainment',
'52': 'Activision',
'53': 'Sammy USA Corporation',
'54': 'GameTek',
'55': 'Park Place',
'56': 'LJN',
'57': 'Matchbox',
'59': 'Milton Bradley Company',
'5A': 'Mindscape',
'5B': 'Romstar',
'5C': 'Naxat Soft',
'5D': 'Tradewest',
'60': 'Titus Interactive',
'61': 'Virgin Games Ltd.',
'67': 'Ocean Software',
'69': 'EA (Electronic Arts)',
'6E': 'Elite Systems',
'6F': 'Electro Brain',
'70': 'Infogrames',
'71': 'Interplay Entertainment',
'72': 'Broderbund',
'73': 'Sculptured Software',
'75': 'The Sales Curve Limited',
'78': 'THQ',
'79': 'Accolade',
'7A': 'Triffix Entertainment',
'7C': 'MicroProse',
'7F': 'Kemco',
'80': 'Misawa Entertainment',
'83': 'LOZC G.',
'86': 'Tokuma Shoten',
'8B': 'Bullet-Proof Software',
'8C': 'Vic Tokai Corp.',
'8E': 'Ape Inc.',
'8F': 'I’Max',
'91': 'Chunsoft Co.',
'92': 'Video System',
'93': 'Tsubaraya Productions',
'95': 'Varie',
'96': 'Yonezawa10/S’Pal',
'97': 'Kemco',
'99': 'Arc',
'9A': 'Nihon Bussan',
'9B': 'Tecmo',
'9C': 'Imagineer',
'9D': 'Banpresto',
'9F': 'Nova',
'A1': 'Hori Electric',
'A2': 'Bandai',
'A4': 'Konami',
'A6': 'Kawada',
'A7': 'Takara',
'A9': 'Technos Japan',
'AA': 'Broderbund',
'AC': 'Toei Animation',
'AD': 'Toho',
'AF': 'Namco',
'B0': 'Acclaim Entertainment',
'B1': 'ASCII Corporation or Nexsoft',
'B2': 'Bandai',
'B4': 'Square Enix',
'B6': 'HAL Laboratory',
'B7': 'SNK',
'B9': 'Pony Canyon',
'BA': 'Culture Brain',
'BB': 'Sunsoft',
'BD': 'Sony Imagesoft',
'BF': 'Sammy Corporation',
'C0': 'Taito',
'C2': 'Kemco',
'C3': 'Square',
'C4': 'Tokuma Shoten',
'C5': 'Data East',
'C6': 'Tonkin House',
'C8': 'Koei',
'C9': 'UFL',
'CA': 'Ultra Games',
'CB': 'VAP, Inc.',
'CC': 'Use Corporation',
'CD': 'Meldac',
'CE': 'Pony Canyon',
'CF': 'Angel',
'D0': 'Taito',
'D1': 'SOFEL (Software Engineering Lab)',
'D2': 'Quest',
'D3': 'Sigma Enterprises',
'D4': 'ASK Kodansha Co.',
'D6': 'Naxat Soft',
'D7': 'Copya System',
'D9': 'Banpresto',
'DA': 'Tomy',
'DB': 'LJN',
'DD': 'Nippon Computer Systems',
'DE': 'Human Ent.',
'DF': 'Altron',
'E0': 'Jaleco',
'E1': 'Towa Chiki',
'E2': 'Yutaka',
'E3': 'Varie',
'E5': 'Epoch',
'E7': 'Athena',
'E8': 'Asmik Ace Entertainment',
'E9': 'Natsume',
'EA': 'King Records',
'EB': 'Atlus',
'EC': 'Epic/Sony Records',
'EE': 'IGS',
'F0': 'A Wave',
'F3': 'Extreme Entertainment',
'FF': 'LJN'
}